### ISSUE TITLE
Video Content attribute missing for 7.7 model

### ISSUE THREAD

**Issue by FredrikNoren** [lo48576/fbxcel#6]
Hi, I'm trying to load a model, which when loaded with blender does have textures, but when I'm loading it with fbxcel I'm missing a texture. When doing a dump I can see that one of the video nodes is missing a binary attribute on the content node:

```
     Video I64(88248016), String("vanguard_vanguard_diffuse_tga\0\u{1}Video"), String("Clip")
       Type String("Clip")
       Properties70 
         P String("Path"), String("KString"), String("XRefUrl"), String(""), String("/home/app/mixamo-mini/tmp/skins_7dd7371a-8200-435c-9d7d-9d7ab1caebc2.fbm/vanguard_diffuse1.png")
         P String("RelPath"), String("KString"), String("XRefUrl"), String(""), String("../../../../home/app/mixamo-mini/tmp/skins_7dd7371a-8200-435c-9d7d-9d7ab1caebc2.fbm/vanguard_diffuse1.png")
       UseMipMap I32(0)
       Filename String("/home/app/mixamo-mini/tmp/skins_7dd7371a-8200-435c-9d7d-9d7ab1caebc2.fbm/vanguard_diffuse1.png")
       RelativeFilename String("../../../../home/app/mixamo-mini/tmp/skins_7dd7371a-8200-435c-9d7d-9d7ab1caebc2.fbm/vanguard_diffuse1.png")
       Content 
```

(I.e. there are no attributes after `Content`. It should look something like this: `Content Binary([137, 80, 78, 71, 13,...`)

Some of the other ones do seem to work though. I'm not sure if this is because it's 7.7 (rather than 7.5)? I've attached the model and a dump of the model.

[Vanguard By T. Choonyung Binary.fbx.txt.zip](https://github.com/lo48576/fbxcel/files/9600877/Vanguard.By.T.Choonyung.Binary.fbx.txt.zip)
[Vanguard By T. Choonyung Binary.fbx.zip](https://github.com/lo48576/fbxcel/files/9600883/Vanguard.By.T.Choonyung.Binary.fbx.zip)

**Comment by FredrikNoren** [comment]
Also; thanks for an amazing library :)

**Comment by FredrikNoren** [comment]
Hm, actually I'm starting to believe this is some kind of optimization by FBX; I can see that there's another Video node with the same filename, which does have Content. I'm just going to assume that it's probably meant to resolve those together based on filename or something.

**Comment by lo48576** [comment]
The `Content` under Video (Clip) node is optional, and will be available if the FBX data generator (exporter) chose to embed textures to the file. It seems blender supports embedding texture, so try it ([Include textures in FBX files | 3D Repo Help Centre](https://help.3drepo.io/en/articles/4768925-include-textures-in-fbx-files), <https://blenderartists.org/t/cant-embed-textures-inside-fbx/1112216/8>).

I don't know how the non-embedded textures should be resolved, but I think it should usually be done by the downstream codes since file path lookup could be optimized in app-specific way (e.g. caching, on-demand online fetching, seamless access to zip-archives, etc.).
