### ISSUE TITLE
load an FBX, modify it, then export it

### ISSUE THREAD

**Issue by birdistheword96** [lo48576/fbxcel#7]
I see that there is a reader and a writer, but it seems like the reader and writer are detached and cannot be converted. This means that for the writer you have to start from a blank object and then perhaps copy across each node or something?

Is there an easy way to read in an FBX file, modify it slightly, then output it again?

**Comment by lo48576** [comment]
What I should ask you is, how much performance and robustness you need? And, what kind of modification do you attempt to?

Readers and writers are implemented so that they can avoid allocation as possible. Readers provide a way to read (or skip) the data sequentially, rather than returning allocated "node" objects. Writers also provide a way to write each attributes or array elements, rather than receiving allocated "node" objects. Consequently, users are required to pass node name and each attribute one by one from a reader to a writer.

If you can accept loading all nodes on a memory at once, then the easiest way will be loading everything into a [`Tree`](https://docs.rs/fbxcel/0.8.1/fbxcel/tree/v7400/struct.Tree.html) and writing it using [`Writer::write_tree`](https://docs.rs/fbxcel/latest/fbxcel/writer/v7400/binary/struct.Writer.html#method.write_tree).
(The tree type lacks methods to remove nodes, so possibly I should implement such API if you need...)

However, if you are willing to process untrusted or possibly quite big data, then I think you should stick to the raw readers and writers in order to prevent OOM errors. Even allocating "a node" on memory can require gigabytes of buffers.

**Comment by birdistheword96** [comment]
Thanks for the information, I wasn't aware the allocation would be so high! Essentially I need to load an existing FBX file, modify the animation data within it by changing the times and keyframe data, then write the file back as a new file.  I would also need to modify a few bits of Metadata throughout the file, such a time of creation, author, etc.
I'm having a load of issues with the native FBX library provided by Autodesk (using both the main C API and the Python bindings) and having had great success in writing a re-writing a few tools in rust recently, I was hoping to be able to do it using rust.

**Comment by lo48576** [comment]
Just now I published v0.8.2, which contains some more tree manipulation methods. See the [CHANGELOG](https://github.com/lo48576/fbxcel/blob/v0.8.2/CHANGELOG.md#added) for the list of the added items, or [documentation of the `Tree` type](https://docs.rs/fbxcel/0.8.2/fbxcel/tree/v7400/struct.Tree.html#tree-manipulation-methods) for the list of available manipulation methods.

I think they enable you to modify or create an arbitrary FBX tree data you want. Once you edited the tree, now you can use [`Writer::write_tree()`](https://docs.rs/fbxcel/0.8.2/fbxcel/writer/v7400/binary/struct.Writer.html#method.write_tree).

If these methods did not help you, feel free to comment or reopen the issue.
